### ISSUE TITLE
The installation failed. I' am facing an issue while installing SoundFlower.

### ISSUE THREAD

**Issue by hardeep-singh** [RogueAmoeba/Soundflower#79]
Mac version is 10.13.4.
The error message is:- The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.

**Comment by thowi** [comment]
Same problem.
Console shows:
default	22:22:37.780358 +0200	kextd	Kext rejected due to system policy: <OSKext 0x7fd3e43168e0 [0x7fff9a194af0]> { URL = "file:///Library/StagedExtensions/Library/Extensions/Soundflower.kext/", ID = "com.Cycling74.driver.Soundflower" }
default	22:22:37.780457 +0200	kextd	com.Cycling74.driver.Soundflower failed security checks; failing.

**Comment by thowi** [comment]
Probably a bug in the installer:
https://developer.apple.com/library/content/technotes/tn2459/_index.html#//apple_ref/doc/uid/DTS40017658-CH1-TNTAG3

**Comment by Erallie** [comment]
If you're using High Sierra, I read somewhere in a description somewhere that it will fail the first time, and then you need to go to your system preferences and allow an extension to be installed manually from the security and privacy pane, and then it should work.

"IF INSTALLING ON HIGH SIERRA
The first attempt to install will display a security alert, then fail. Afterwards, you need to go into System Preferences "Security & Privacy - General" pane and give permission to allow the install signed by the developer "MATT INGALLS". After giving permission, you will be able to run the installer successfully."
https://github.com/mattingalls/Soundflower/releases/tag/2.0b2

I have a similar problem, though. For me, I have to manually allow my mac to open the package that opens the installer, and then the installer failed, but it didn't show another thing for me to allow permissions to open or install on my mac. I restarted my computer, and it still didn't help!

**Comment by wAuner** [comment]
Still having the problem. Any update on this?

**Comment by mattingalls** [comment]
@wAuner email me matt@sonomatics.com with exact details of what you are doing and i can try to help

**Comment by eclab** [comment]
The problem occurs on High Sierra regardless of whether you've given security permission.

Step 1.  Run the installer.
Step 2. Go to System Preferences Security & Privacy and give permission.
Step 3. Continue to run the installer (or quit it and run it again).
Step 4.  "The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance."
Step 5. Grumble a lot and run the uninstallation script.

**Comment by ahaverdings** [comment]
For me the problem was that I could now "Allow" the application. [https://apple.stackexchange.com/questions/323668/allow-button-not-working-in-system-preferences](https://apple.stackexchange.com/questions/323668/allow-button-not-working-in-system-preferences) this thread showed me (not the accepted answer) in the log that Garageband was not shut down and making external connection with my ipad preventing the "Allow". Once I broke the connection I could press allow and the installation was successful.

**Comment by moduloapparent** [comment]
_"For anyone struggling with a failed installation of soundflower 2, what you need to do is attempt the install, and when it says that it has failed, DO NOT CLOSE THE WINDOW. At that point make sure you quit system preferences, re-open system preferences, and under Security & Privacy, click allow where it says Matt Ingals has been blocked from opening. After that, close the window with the failed installation, and attempt the installation again. It should work properly.﻿"_

I found the solution in the comments section from Maximus De on Youtube to this video: https://www.youtube.com/watch?v=kxx0gNyfXV8
The method in the video itself did *not* work for me, but the comment from Maximus did.

**Comment by eclab** [comment]
That video has the feel of voodoo rather than solution.

However, I *have* been able to get Soundflower installed by bypassing the graphical installer entirely and using the "install" terminal command.  Hopefully this repeatable positive example should be enough to help the developers nail down the problem with their installer package.  It looks like something (perhaps a timeout?) is causing the graphical installer to fail prematurely.

1. Unpack the Soundflower-2.0b2.dmg disk image.
2. In the terminal, type:
    cd /Volumes/Soundflower-2.0b2
3. Then: 
    sudo installer -pkg Soundflower.pkg -target /
    [type in your password if prompted]
4. When you’re told that this has failed, go to “Security and Privacy” in System Preferences, and permit the software to load.  You may need to click ”Allow...”, then select “MATT INGALLS”. Then do steps 2 and 3 again.
5. Wait a long time. It takes quite a while to install for no good reason.  [I suspect the problem with the package is here]
6. At this point, SoundFlower2ch and 64ch will appear as audio devices.

**Comment by lummish** [comment]
@eclab Spent the last 3 Hours messing with Xcode project settings to no avail but this works beautifully!

**Comment by Shaolo** [comment]
eclabs instructions worked for me.

**Comment by rahatlukumich** [comment]
I had the same problem as ahaverdings, but in my case it was iMovie that was preventing the "Allow".

**Comment by meldiwin** [comment]
> _"For anyone struggling with a failed installation of soundflower 2, what you need to do is attempt the install, and when it says that it has failed, DO NOT CLOSE THE WINDOW. At that point make sure you quit system preferences, re-open system preferences, and under Security & Privacy, click allow where it says Matt Ingals has been blocked from opening. After that, close the window with the failed installation, and attempt the installation again. It should work properly.﻿"_
> 
> I found the solution in the comments section from Maximus De on Youtube to this video: https://www.youtube.com/watch?v=kxx0gNyfXV8
> The method in the video itself did _not_ work for me, but the comment from Maximus did.

Thanks so much, It worked perfectly.

**Comment by julianknowles01** [comment]
On High Sierra - make sure you quit all applications before running the installer. I was having the same errors and then I quit everything and followed the Terminal installation instructions above and it finally worked. YMMV

**Comment by eyexx** [comment]
@eclab  it worked for me!  thanks

**Comment by aquaty** [comment]
The problem occurs on Mojave with no option to give security permission.

Step 1. Run the installer 
Step 2. it fails "The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance."
Step 3. Tried installing from terminal   sudo installer -pkg Soundflower.pkg -target /
and brew cask install soundflower, same error 
Step 4. Go to System Preferences Security & Privacy and do not see option to give permission.
Step 5. Continue to run the installer (or quit it and run it again), and restart System Preferences Security, same error, no prompt for permission 

error from homebrew
```
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:65:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:34:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:218:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:103:in `<main>'
```

**Comment by gabrielturielle** [comment]
Hello, ther's a new app named BlackHole instead of SoundFlower. I've installed and it's works great!

https://github.com/ExistentialAudio/BlackHole

**Comment by Gabbibada** [comment]
> That video has the feel of voodoo rather than solution.
> 
> However, I _have_ been able to get Soundflower installed by bypassing the graphical installer entirely and using the "install" terminal command. Hopefully this repeatable positive example should be enough to help the developers nail down the problem with their installer package. It looks like something (perhaps a timeout?) is causing the graphical installer to fail prematurely.
> 
> 1. Unpack the Soundflower-2.0b2.dmg disk image.
> 2. In the terminal, type:
>    cd /Volumes/Soundflower-2.0b2
> 3. Then:
>    sudo installer -pkg Soundflower.pkg -target /
> 4. When you’re told that this has failed, go to “Security and Privacy” in System Preferences, and permit the software to load.  You may need to click ”Allow...”, then select “MATT INGALLS”. Then do steps 2 and 3 again.
> 5. Wait a long time. It takes quite a while to install for no good reason.  [I suspect the problem with the package is here]
> 6. At this point, SoundFlower2ch and 64ch will appear as audio devices.

Worked for me. Thanks

**Comment by idfx** [comment]
> That video has the feel of voodoo rather than solution.
> 
> However, I _have_ been able to get Soundflower installed by bypassing the graphical installer entirely and using the "install" terminal command. Hopefully this repeatable positive example should be enough to help the developers nail down the problem with their installer package. It looks like something (perhaps a timeout?) is causing the graphical installer to fail prematurely.
> 
> 1. Unpack the Soundflower-2.0b2.dmg disk image.
> 2. In the terminal, type:
>    cd /Volumes/Soundflower-2.0b2
> 3. Then:
>    sudo installer -pkg Soundflower.pkg -target /
> 4. When you’re told that this has failed, go to “Security and Privacy” in System Preferences, and permit the software to load.  You may need to click ”Allow...”, then select “MATT INGALLS”. Then do steps 2 and 3 again.
> 5. Wait a long time. It takes quite a while to install for no good reason.  [I suspect the problem with the package is here]
> 6. At this point, SoundFlower2ch and 64ch will appear as audio devices.

Worked for me as well!

**Comment by XABUNO** [comment]
> _"For anyone struggling with a failed installation of soundflower 2, what you need to do is attempt the install, and when it says that it has failed, DO NOT CLOSE THE WINDOW. At that point make sure you quit system preferences, re-open system preferences, and under Security & Privacy, click allow where it says Matt Ingals has been blocked from opening. After that, close the window with the failed installation, and attempt the installation again. It should work properly.﻿"_
> 
> I found the solution in the comments section from Maximus De on Youtube to this video: https://www.youtube.com/watch?v=kxx0gNyfXV8
> The method in the video itself did _not_ work for me, but the comment from Maximus did.

This works perfectly for me. Thank you!

**Comment by gdudek** [comment]
The solution from moduloapparent worked well for me (as for others).  It's not "voodoo". It's because the signing authority required isn't remembered for non-apps after the program exits (which is super annoying).  You could also turnoff integrity protection, I guess.

**Comment by brucethomax** [comment]
I am still having a failure after granting permission.

`installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “Soundflower.pkg”.)`

**Comment by aeaeaeaeaeae** [comment]
Having the same experience as @thomasbeauvais, on macOS Big Sur 

```
sudo installer -pkg Soundflower.pkg -target /
Password:
installer: Package name is Soundflower
installer: Installing at base path /
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “Soundflower.pkg”.
```

**Comment by gdudek** [comment]
> Having the same experience as @thomasbeauvais, on macOS Big Sur
> 
> ```
> sudo installer -pkg Soundflower.pkg -target /
> Password:
> installer: Package name is Soundflower
> installer: Installing at base path /
> installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “Soundflower.pkg”.
> ```

What do you see in the Console, associated with this error?

**Comment by aeaeaeaeaeae** [comment]
@gdudek what I posted above was the entire print-out, the following is with `sudo installer -verbose -pkg Soundflower.pkg -target /`

```
installer: Package name is Soundflower
installer: Installing at base path /
installer: Preparing for installation….....
installer: Preparing the disk….....
installer: Preparing Soundflower….....
installer: Waiting for other installations to complete….....
installer: Configuring the installation….....
installer:
#
installer: Running package scripts….....
#
installer: Running package scripts….....
#
installer: Running package scripts….....
#
installer: Running package scripts….....
installer: Running package scripts….....
installer: Running package scripts….....
installer: Running package scripts….....
installer: Running package scripts….....
installer: Running package scripts….....
installer: Running package scripts….....
installer: Running package scripts….....
installer: Running package scripts….....
installer: Running package scripts….....
installer: Running package scripts….....
installer: Running package scripts….....
installer: Running package scripts….....
installer: Validating packages….....
#
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “Soundflower.pkg”.)
```

**Comment by Jahnzilla** [comment]
Unfortunately I'm unable to get this installed on Macbook Pro 2021 with Big Sur. I get to the stage where I open Security & Privacy upon the failed installation but no option to say a blocked application from Matt Ingals shows. Has anyone else had success with Big Sur?

**Comment by mechanicalpencilwitheraser** [comment]
I have the same issue with Jahnzilla, I even restarted and went to startup security utility and cicked it to be from full security to reduced security and when i restarted it was the same situation. there is no option to allow anything else in security and privacy. and all this, because i am trying to cast sound from my desktop (VLC) to my chromecast. I would greatly appreciate a solution
